# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  name: 'AzSpherePool'

variables:
  solution: '**/*.sln'
  buildPlatform: 'ARM'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "##vso[task.setvariable variable=buildid;]$Build.BuildId"
      Write-Host "##vso[task.setvariable variable=srcdir;]$Build.SourcesDirectory"

      Write-Host "($buildid)"
      Write-Host "($srcdir)"

      Write-Host "$(Build.BuildId)"
      Write-Host "$(Build.SourcesDirectory)"
      
      (Get-Content ($Build.SourcesDirectory)\SphereApp\main.c) | 
      Foreach-Object {$_ -replace "#VERSION_NUMBER", "($Build.BuildId)"} | 
      Set-Content ($Build.SourcesDirectory)\SphereApp\main.c

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)\SphereApp\bin\ARM\Release\SphereApp.imagepackage'
    ArtifactName: 'drop'
    publishLocation: 'Container'
